name: travs
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  animate_do: ^3.3.7
  animated_hint_textfield: ^1.0.3
  animated_text_kit: ^4.2.3
  bounce: ^1.0.2
  flutter:
    sdk: flutter
  flutter_card_swiper: ^7.0.2
  flutter_dotenv: ^5.2.1
  flutter_svg: ^2.0.17
  get: ^4.6.6
  http: ^1.3.0
  readmore: ^3.0.0
  shimmer: ^3.0.0
  supabase_flutter: ^2.8.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/weather/
    - assets/destinations.json
    - .env
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
